trigger: none

parameters:

  - name: azureServiceConnection
    type: string

  - name: environment
    displayName: 'Deployment Environment'
    type: string
    default: 'nonProd'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: /vars/${{ parameters.environment }}-vars.yml
  - name: pipelineType
    value: 'Infrastructure'

resources:
  repositories:
    - repository: templates
      type: git
      name: azureInfra/templates

stages:
  - stage: DeployKeyVault
    displayName: 'Deploy Key Vault'
    jobs:
      - job: Deploy
        displayName: 'Deploy Key Vault to $(environment)'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - script: |
              az bicep build --file modules/Keyvault/keyVault.bicep --outdir modules/Keyvault/
            name: LintBicepCode
            displayName: 'IaC Linter - Bicep Build'

          - task: AzureCLI@2
            name: RunPreFlightChecks
            displayName: 'Run Pre-Flight Checks'
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Running pre-flight checks..."
                # Add your pre-flight check commands here
                az deployment group validate \
                  --resource-group $(resourceGroupName) \
                  --template-file modules/Keyvault/keyVault.json \
                  --parameters modules/Keyvault/keyVault-$(environment)-parameters.json

          - task: AzureCLI@2
            name: DeployKeyVault
            displayName: 'Deploy Key Vault'
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Deploying Key Vault..."
                az deployment group create \
                  --resource-group $(resourceGroupName) \
                  --template-file modules/Keyvault/keyVault.json \
                  --parameters modules/Keyvault/keyVault-$(environment)-parameters.json