trigger: none

parameters:
  - name: azureServiceConnection
    type: string
    values:
      - 'AzureServiceConnection1'
      - 'AzureServiceConnection2'

  - name: environment
    type: string
    default: 'nonProd'
    values:
      - nonProd
      - prod

resources:
  repositories:
    - repository: templates
      type: git
      name: azureInfra/templates

variables:
  - templates: /vars/${{ parameters.environment }}-vars.yml

agents:
  pool:
    vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy_keyVault
    displayName: 'Deploy keyVault'
    jobs:
      - job: Deploy_keyVault
        displayName: 'Deploy keyVault'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: modules/Keyvault/keyVault.yml
            parameters:
              environment: ${{ parameters.environment }}
              azureServiceConnection: ${{ parameters.azureServiceConnection }} 